# Introduction to NumPy

## Creating Arrays from Scratch

IT is more efficient to create arrays from scratch using routines built into NumPy.

In [30]:
import numpy as np
np.zeros(10, dtype = int)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Create a 3x5 array of ones and type float

In [31]:
np.ones((3,5,), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Fill a 3x5 array with a certain value.

In [32]:
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

Create an array filled with a linear sequence.

In [33]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

Create an array of five values evenly spaced between 0 and 1

In [34]:
np.linspace(0,5,6)

array([0., 1., 2., 3., 4., 5.])

Create a 3x3 array of uniformly distributed values

In [35]:
np.random.random((3,3))

array([[0.04735302, 0.23886341, 0.94166708],
       [0.18437342, 0.55515818, 0.84845236],
       [0.68681157, 0.51229955, 0.63090349]])

Create a 3x3 array of normally distributed random values with mean = 0 and stdev = 1

In [36]:
np.random.normal(0,1,(3,3))

array([[ 1.82916189, -0.79518908,  0.1473033 ],
       [-0.19986152, -0.07739421,  1.27786949],
       [ 2.41530134, -0.03855889, -1.09069922]])

Create a 3x3 array of rand ints in [0,10)

In [37]:
np.random.randint(0,10,(3,3))

array([[7, 1, 4],
       [6, 7, 2],
       [1, 9, 5]])

Create a 3x3 identity matrix

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])